### ISSUE TITLE
Specific upload for user is consistently failing

### ISSUE THREAD

**Issue by jlhogan** [ctoec/component-library#121]
## Background
Specific file upload is failing for a specific user, preventing her from moving forward.  Failing upload will be attached shortly.

## Acceptance Criteria
- Files that fail to be parsed are **not** deleted from disk
   - Consider adding timestamp to filename for simpler debugging
- File upload in this specific case for this specific user succeeds

## Stacktrace
```
        2021-01-19T13:22:35.118-05:00	Jan 19 18:22:35 ip-10-0-40-147 web: Unable to determine validation errors in spreadsheet: TypeError: Cannot read property 'forEach' of undefined
	2021-01-19T13:22:35.118-05:00	Jan 19 18:22:35 ip-10-0-40-147 web: at Array.<anonymous> (/var/app/current/dist/src/entity/Enrollment.js:107:29)
	2021-01-19T13:22:35.118-05:00	Jan 19 18:22:35 ip-10-0-40-147 web: at /var/app/current/node_modules/class-validator/bundles/index.umd.js:463:74
	2021-01-19T13:22:35.118-05:00	Jan 19 18:22:35 ip-10-0-40-147 web: at Array.map (<anonymous>)
	2021-01-19T13:22:35.118-05:00	Jan 19 18:22:35 ip-10-0-40-147 web: at ValidationExecutor.conditionalValidations (/var/app/current/node_modules/class-validator/bundles/index.umd.js:463:18)
	2021-01-19T13:22:35.118-05:00	Jan 19 18:22:35 ip-10-0-40-147 web: at ValidationExecutor.performValidations (/var/app/current/node_modules/class-validator/bundles/index.umd.js:423:36)
	2021-01-19T13:22:35.118-05:00	Jan 19 18:22:35 ip-10-0-40-147 web: at /var/app/current/node_modules/class-validator/bundles/index.umd.js:368:27
	2021-01-19T13:22:35.118-05:00	Jan 19 18:22:35 ip-10-0-40-147 web: at Array.forEach (<anonymous>)
	2021-01-19T13:22:35.118-05:00	Jan 19 18:22:35 ip-10-0-40-147 web: at ValidationExecutor.execute (/var/app/current/node_modules/class-validator/bundles/index.umd.js:358:43)
	2021-01-19T13:22:35.118-05:00	Jan 19 18:22:35 ip-10-0-40-147 web: at /var/app/current/node_modules/class-validator/bundles/index.umd.js:561:27
	2021-01-19T13:22:35.368-05:00	Jan 19 18:22:35 ip-10-0-40-147 web: at Array.forEach (<anonymous>)
	2021-01-19T13:22:35.368-05:00	Jan 19 18:22:35 ip-10-0-40-147 web: query: ROLLBACK -- PARAMETERS: ["redacted"]
	2021-01-19T13:22:41.231-05:00	Jan 19 18:22:35 ip-10-0-40-147 web: ::ffff:127.0.0.1 - 19 [19/Jan/2021:18:22:35 +0000] "POST /api/enrollment-reports/check HTTP/1.0" 400 151
```

**Comment by bamader** [comment]
This bug seems to be preventing the `uploadMissingSome` e2e test from completing in qa too (found that when checking the cloudwatch logs after trying and failing several times to merge a  PR).

**Comment by bamader** [comment]
Also any reason this is in the component library board instead of the data collection board? Was confused when I didn't see it there.

**Comment by JordanGuinn** [comment]
@bamader Nope - probably an accident when this ticket was created.  Moving forward though, I'd recommend toggling the `Repos` filter to display _all_ repositories on the dev board (which I really wish ZenHub made the default).

**Comment by jlhogan** [comment]
@bamader if you're able to repro this error without waiting for Antoinette's file (i.e. with the missing some upload from e2e tests!) then we can get started on this right away, which would be awesome!

**Comment by JordanGuinn** [comment]
## Test Cases
- [ ] File upload of enrollments w/ valid fundings succeeds
- [ ] File upload of enrollments w/ invalid fundings succeeds
- [ ] File upload of enrollments w/ no fundings succeeds
- [ ] Failed file upload (for external reasons) persists file to instance, with timestamp

**Comment by JordanGuinn** [comment]
Looks good to me - moving to `Ready`.

**Comment by victoriasuwardiman** [comment]
Er do y'all still need the file? lol also, it's not allowing me to attach an xlsx or csv file so let me know and I can email it to you

**Comment by JordanGuinn** [comment]
@victoriasuwardiman Nah I think we're good 🙂
